// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nnmxsydpoaiwfcuofcjy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ubXhzeWRwb2Fpd2ZjdW9mY2p5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNTcyNDUsImV4cCI6MjA2MDczMzI0NX0.LSq_TwQIQzrUzkhpYOi_jrpGqITjkLTcehE6Ave9hqA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);